auth0:
  auth0_domain:
    default: 'auth.mozilla.auth0.com'
    shadowed_by_global: true
  auth0_client_id:
    default: ''
    shadowed_by_global: true
  auth0_client_secret:
    default: ''
    shadowed_by_global: true
mozilla_iam:
  mozilla_iam_person_api_url:
    default: 'https://person-api.sso.mozilla.com'
    shadowed_by_global: true
  mozilla_iam_person_api_aud:
    default: 'https://person-api.sso.mozilla.com'
    shadowed_by_global: true
  mozilla_iam_person_v2_api_url:
    default: "https://person.api.test.sso.allizom.org"
    shadowed_by_global: true
  mozilla_iam_person_v2_api_aud:
    default: "api.test.sso.allizom.org"
    shadowed_by_global: true
  dinopark_url:
    default: "https://dinopark.k8s.test.sso.allizom.org/"
    shadowed_by_global: true
    client: true
  dinopark_avatars_enabled:
    default: true
  dinopark_authorized_groups:
    default: "mozilliansorg_dinopark-preview-access"
    type: list
  mozilla_iam_notification_aud:
    default: "hook.sso.mozilla.com"
    shadowed_by_global: true
