auth0:
  auth0_domain:
    default: 'auth.mozilla.auth0.com'
    shadowed_by_global: true
  auth0_client_id:
    default: ''
    shadowed_by_global: true
  auth0_client_secret:
    default: ''
    shadowed_by_global: true
mozilla_iam:
  mozilla_iam_person_api_url:
    default: 'https://uhbz4h3wa8.execute-api.us-west-2.amazonaws.com/prod'
    shadowed_by_global: true
  mozilla_iam_person_api_aud:
    default: 'https://person-api.sso.mozilla.com'
    shadowed_by_global: true
